//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.PetHead = new HashSet<PetHead>();
        }
    
        public int PetId { get; set; }
        public string PetName { get; set; }
        public string PetStartTime { get; set; }
        public string PetInType { get; set; }
        public string PetType { get; set; }
        public Nullable<int> PetInventory { get; set; }
        public string PetBodily { get; set; }
        public Nullable<double> PetPrice { get; set; }
        public Nullable<int> PetState { get; set; }
        public Nullable<int> UsersId { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PetHead> PetHead { get; set; }
    }
}
