//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderMassage = new HashSet<OrderMassage>();
            this.ProductHead = new HashSet<ProductHead>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Productdescribe { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<int> ProductInventory { get; set; }
        public Nullable<int> ProductState { get; set; }
        public Nullable<int> UsersId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMassage> OrderMassage { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductHead> ProductHead { get; set; }
    }
}
